const { Schema, model } = require('mongoose');

const logs = Schema({
    _id: String,
    ModerationEvents: {
        Toggle: { type: Boolean, default: false },
        BanToggle: { type: Boolean, default: false },
        KickToggle: { type: Boolean, default: false },
        RoleToggle: { type: Boolean, default: false },
        PurgeToggle: { type: Boolean, default: false },
        LockToggle: { type: Boolean, default: false },
        WarnToggle: { type: Boolean, default: false },
        ReportToggle: { type: Boolean, default: false },
        MuteToggle: { type: Boolean, default: false },
        SlowmodeToggle: { type: Boolean, default: false },
        NicknameToggle: { type: Boolean, default: false },
        LogChannel: { type: String, default: null },
        EmbedColor: { type: String, default: null },
    },
    ServerEvents: {
        Toggle: { type: Boolean, default: false },
        VoiceJoinToggle: { type: Boolean, default: false },
        VoiceMoveToggle: { type: Boolean, default: false },
        VoiceStreamingToggle: { type: Boolean, default: false },
        VoiceDeafenToggle: { type: Boolean, default: false },
        ChannelCreateToggle: { type: Boolean, default: false },
        ChannelUpdateToggle: { type: Boolean, default: false },
        ChannelDeleteToggle: { type: Boolean, default: false },
        RoleCreateToggle: { type: Boolean, default: false },
        RoleUpdateToggle: { type: Boolean, default: false },
        GuildUpdateToggle: { type: Boolean, default: false },
        EmojiUpdateToggle: { type: Boolean, default: false },
        MemberJoinToggle: { type: Boolean, default: false },
        MemberLeaveToggle: { type: Boolean, default: false },
        BoostToggle: { type: Boolean, default: false },
        TicketingToggle: { type: Boolean, default: false },
        ThreadCreateToggle: { type: Boolean, default: false },
        ThreadDeleteToggle: { type: Boolean, default: false },
        ThreadUpdateToggle: { type: Boolean, default: false },
        ThreadMembersUpdateToggle: { type: Boolean, default: false },
        StickerCreateToggle: { type: Boolean, default: false },
        StickerDeleteToggle: { type: Boolean, default: false },
        StickerUpdateToggle: { type: Boolean, default: false },
        InviteToggle: { type: Boolean, default: false },
        LogChannel: { type: String, default: null },
        EmbedColor: { type: String, default: null },
    },
    MemberEvents: {
        Toggle: { type: Boolean, default: false },
        RoleUpdateToggle: { type: Boolean, default: false },
        NameChangesToggle: { type: Boolean, default: false },
        DiscriminatorChangesToggle: { type: Boolean, default: false },
        AvatarChangesToggle: { type: Boolean, default: false },
        LogChannel: { type: String, default: null },
        EmbedColor: { type: String, default: null },
    },
    MessageEvents: {
        Toggle: { type: Boolean, default: false },
        DeletedToggle: { type: Boolean, default: false },
        EditedToggle: { type: Boolean, default: false },
        PurgedToggle: { type: Boolean, default: false },
        ReactionToggle: { type: Boolean, default: false },
        LogChannel: { type: String, default: null },
        IgnoreBot: { type: Boolean, default: false },
        EmbedColor: { type: String, default: null },
    },
});

module.exports = model('logs', logs);