const config = {
	ownerID: [''],
	ownerName: '',
	client_id: "",
	secret: "",
	token: '',
	disabledCommands: [],
	disabledFeatures: [],
	websiteURL: '',
	Botlist: {
		Topgg: '',
		Voidbots: '',
		DiscordBotList: '',
	},
	VoteChannel: {
		Topgg: '',
		Voidbots: '',
		DiscordBotList: '',
	},
	SupportServer: {
		link: '',
		GuildID: '',
		GuildChannel: '',
		DefaultInvite: '',
		RecommendedInvite: '',
		FullPermissions: '',
		NoModerator: '',
		BasicPermissions: '',
	},
	MongoDBURL: '',
	rateLimitChannelID: '',
	embedColor: '',
	WebHooks: [
		{ ID: '', TOKEN: '' },
		{ ID: '', TOKEN: '' },
		{ ID: '', TOKEN: '' },
		{ ID: '', TOKEN: '' },
		{ ID: '', TOKEN: '' },
		{ ID: '', TOKEN: '' },
		{ ID: '', TOKEN: '' },
	],
	debug: false,
};

module.exports = config;